In [87]:
import os
import numpy as np
import collections
import pandas as pd

In [88]:
just_names = []

for n in os.listdir("D:/dai/New folder"):
    just_names.append(n.split("_")[0])

In [89]:
npk = np.array(just_names)

In [90]:
collections.Counter(npk)

Counter({'combined': 2,
         'kannada': 2,
         'code': 1,
         'count.csv': 1,
         'csvs': 1,
         'test': 1,
         'test.ipynb': 1})

In [91]:
csv_files = os.listdir("D:/dai/New folder/csvs")

In [92]:
csv_files

['ಅಕ್ಷರ_ಲಿಪಿ_20250208_191035.csv',
 'ಅಕ್ಷರ_ವಿದ್ಯೆ_20250208_191945.csv',
 'ಅಡಿ_12 ಅಂಗುಲದ ಉದ್ದಳತೆ_20250207_182509.csv',
 'ಅಡಿ_ಕೆಳಗೆ_20250207_181711.csv',
 'ಅಶೋಕ_ಒಂದು ಜಾತಿಯ ಮರ_20250208_143829.csv',
 'ಅಶೋಕ_ದುಃಖರಹಿತನಾದವನು_20250208_144009.csv',
 'ಆಟ_ಕ್ರೀಡೆ_20250208_062413.csv',
 'ಆಟ_ನಾಟಕ_20250208_063834.csv',
 'ಉತ್ತರ_ಉತ್ತರದಿಕ್ಕು_20250212_143210.csv',
 'ಉತ್ತರ_ಪ್ರಶ್ನೆಗೆ ಕೊಡುವ ಮರುನುಡಿ_20250207_104113.csv',
 'ಎಳೆ_ಎಳೆತನ, ಬಾಲ್ಯ_20250208_102846.csv',
 'ಎಳೆ_ನೂಲಿನ ಎಳೆ, ಸೂತ್ರ_20250208_101758.csv',
 'ಕಣ_ಧಾನ್ಯಗಳನ್ನು ಒಕ್ಕುವುದಕ್ಕಾಗಿ ಸಿದ್ಧಪಡಿಸಿದ ಸ್ಥಳ_20250208_175950.csv',
 'ಕಣ_ಪದಾರ್ಥದ ಅತ್ಯಂತ ಸೂಕ್ಷ್ಮವಾದ ಅಂಶ_ಅಣು_20250208_175525.csv',
 'ಕಣ_ರಣರಂಗ_20250208_174303.csv',
 'ಕರ_ತೆರಿಗೆ_20250207_111104.csv',
 'ಕರ_ಹಸ್ತ_20250207_140737.csv',
 'ಕರ್ಮ_ಕೆಲಸ_20250205_062110.csv',
 'ಕರ್ಮ_ಸುಖದುಃಖಗಳಿಗೆ ಕಾರಣವಾದ ಪೂರ್ವಜನ್ಮದ ಕಾರ್ಯ_20250204_062053.csv',
 'ಕಲೆ_ಕೊಳೆ, ಕಳಂಕ_20250207_150423.csv',
 'ಕಲೆ_ಲಲಿತವಿದ್ಯೆ, ಕುಶಲವಿದ್ಯೆ_20250207_151803.csv',
 'ಕಳೆ_ಕಾಂತಿ, ತೇಜಸ್ಸು_20250208_080546.csv',
 'ಕಳೆ_ಬೆಳೆಗಳ ನಡುವೆ ಬೆಳೆಯುವ ಹುಲ್ಲು_20250208_081343.csv',
 'ಕಸರತ್ತು_ವ್ಯಾಯಾಮ_20250204_074718.csv',
 'ಕಸರತ್ತು_ಶಕ್ತಿಯ ಹಾಗೂ ಚಮತ್ಕಾರದ ಪ್ರದರ್ಶನ_20250204_055154.csv',
 'ಕೂಲಿ_ಕೂಲಿಯಾಳು_20250207_162216.csv',
 'ಕೂಲಿ_ದುಡಿಮೆಗಾಗಿ ಕೊಡುವ ಪ್ರತಿ ಫಲ_20250207_164934.csv',
 'ಕೇಸರಿ_ಕೇಸರಿ ಬಣ್ಣ_20250208_111252.csv',
 'ಕೇಸರಿ_ಮಸಾಲೆ ಪದಾರ್ಥ_20250208_110122.csv',
 'ಕೈಲಾಸ_ಶಿವನ ನೆಲೆ_20250208_164309.csv',
 'ಕೈಲಾಸ_ಸುಖ, ಆನಂದ_20250208_163848.csv',
 'ಕೈಲಾಸ_ಹಿಮಾಲಯ ಪರ್ವತ ಶ್ರೇಣಿಯಲ್ಲಿರುವ ಒಂದು ಬೆಟ್ಟ_20250208_165519.csv',
 'ಗಜ_ಆನೆ_20250204_170152.csv',
 'ಗಜ_ಒಂದು ಅಳತೆ, ಎರಡು ಮೊಳ, ಮೂರಡಿ ಉದ್ದ_20250204_135930.csv',
 'ಗುಂಡಿ_ಅಂಗಿ ಗುಂಡಿ_20250207_142638.csv',
 'ಗುಂಡಿ_ಒತ್ತುವ ಗುಬುಟು_20250207_142225.csv',
 'ಗುಂಡಿ_ಬಿಲ, ಡೊಗರು, ಗುಣಿ_20250207_141700.csv',
 'ಗುಂಡು_ತುಪಾಕಿಯ ಗೋಲಿ_20250207_170626.csv',
 'ಗುಂಡು_ದುಂಡನೆಯ_20250207_152236.csv',
 'ಗುಡುಗು_ಆರ್ಭಟ_20250202_072311.csv',
 'ಗುಡುಗು_ಮೇಘಗರ್ಜನೆ_20250202_071052.csv',
 'ಗುರು_ಉಪಾಧ್ಯಾಯ_20250206_133429.csv',
 'ಗುರು_ನವ ಗ್ರಹಗಳಲ್ಲಿ ಒಂದು_20250206_134752.csv',
 'ತಿಳಿ_ಜ್ಞಾನ, ಅರಿವು_20250205_184936.csv',
 'ತಿಳಿ_ಸ್ವಚ್ಛತೆ, ನೈರ್ಮಲ್ಯ_20250212_144429.csv',
 'ತೀರ್ಥ_ಕೊಳ, ನದಿ ಜಲಪ್ರದೇಶವಿರುವ ಪುಣ್ಯ ಕ್ಷೇತ್ರ_20250207_063127.csv',
 'ತೀರ್ಥ_ಪವಿತ್ರ ಜಲ_20250207_052926.csv',
 'ತುರಿ_ಒಂದು ಬಗೆಯ ಚರ್ಮರೋಗ_20250205_191022.csv',
 'ತುರಿ_ತೆಂಗಿನಕಾಯಿ ಕೊಬ್ಬರಿ ಹೆರೆ_20250205_192105.csv',
 'ದಂತ_ಆನೆಯ ಕೋರೆ_20250208_065631.csv',
 'ದಂತ_ಹಲ್ಲು, ರದನ_20250208_064809.csv',
 'ದಳ_ಎಲೆ_20250208_150516.csv',
 'ದಳ_ಪಡೆ, ಸೈನ್ಯ_20250208_144546.csv',
 'ದಿವಾಳಿ_ಎಲ್ಲವನ್ನೂ ಕಳೆದುಕೊಳ್ಳುವಿಕೆ_20250205_181241.csv',
 'ದಿವಾಳಿ_ದೀಪಾವಳಿ ಹಬ್ಬ_20250205_141823.csv',
 'ಧರಣಿ_ಭೂಮಿ_20250205_182603.csv',
 'ಧರಣಿ_ಮು__ಷ್ಕರ_20250205_183656.csv',
 'ನರ_ಅವಯವಗಳಿಂದ ಸಂವೇದನೆಗಳನ್ನೂ, ಮೆದುಳಿನಿಂದ ಅವಯವಗಳಿಗೆ ಸೂಚನೆಗಳನ್ನು ಒಯ್ಯುವ - ತಂತು, ಸೆರೆ_20250207_153959.csv',
 'ನರ_ಮನುಷ್ಯ_20250207_183605.csv',
 'ನಾಮ_ಮೋಸ_20250205_150716.csv',
 'ನಾಮ_ಹಣೆಯಲ್ಲಿ ಧರಿಸುವ ಲಾಂಛನ_20250205_152536.csv',
 'ನಾಮ_ಹೆಸರು_20250205_064125.csv',
 'ನಿರ್ಮಾಪಕ_ಚಲನಚಿತ್ರ, ನಾಟಕ ಮುಂ.ವುಗಳ ನಿರ್ಮಾಣಕ್ಕೆ ಹಣವನ್ನು ಒದಗಿಸುವವನು, ಬಂಡವಾಳ ಹಾಕುವವನು_20250208_170754.csv',
 'ನಿರ್ಮಾಪಕ_ಸೃಷ್ಟಿ ಮಾಡುವವನು_20250208_171548.csv',
 'ನೆರೆ_ತುಂಬು ಪ್ರವಾಹ_20250208_143442.csv',
 'ನೆರೆ_ಪಕ್ಕ_20250208_145943.csv',
 'ನೇರ_ನಿಜ, ಸತ್ಯ, ಕಾಲ, ಸಮಯ_20250207_211152.csv',
 'ನೇರ_ನೆಟ್ಟಗಿರುವಿಕೆ, ಡೊಂಕಿಲ್ಲದಿರುವಿಕೆ_20250207_211900.csv',
 'ಪೂರ್ವ_ಮೂಡಣ ದಿಕ್ಕು_20250208_093733.csv',
 'ಪೂರ್ವ_ಹಿಂದೆ_20250208_095419.csv',
 'ಬಂಡವಾಳ_ಬೆಲೆ, ಮೌಲ್ಯ_20250208_150403.csv',
 'ಬಂಡವಾಳ_ಸತ್ವ, ತಿರುಳು_20250208_145457.csv',
 'ಬದಿ_ಕೆಸರು_20250207_143829.csv',
 'ಬದಿ_ಪಕ್ಕ, ಮಗ್ಗಲು_20250207_143607.csv',
 'ಬಯಲು_ಬಹಿರಂಗ_20250208_114559.csv',
 'ಬಯಲು_ಮೈದಾನ_20250208_113423.csv',
 'ಬರೆ_ಕಾದ ಕುಳದಿಂದ ಮೈಮೇಲೆ ಎಳೆದ ಗೆರೆ_20250203_111953.csv',
 'ಬರೆ_ರೇಖೆ_20250203_141326.csv',
 'ಬೆಳೆ_ದೊಡ್ಡದಾಗು_20250207_061614.csv',
 'ಬೆಳೆ_ಬೆಳೆದುದು_ ಮರ, ಗಿಡ, ಪೈರು_20250207_061104.csv',
 'ಭಾವ_ಅಕ್ಕನ ಗಂಡ_20250203_111642.csv',
 'ಭಾವ_ಅಭಿಪ್ರಾಯ_20250202_183127.csv',
 'ಭಾವ_ಗಂಡನ ಅಣ್ಣ_20250202_184452.csv',
 'ಭಾವ_ಹೆಂಡತಿಯ ಅಣ್ಣ_20250202_181758.csv',
 'ಭೂತ_ದೆವ್ವ, ಪಿಶಾಚಿ_20250208_074533.csv',
 'ಭೂತ_ಹಿಂದೆ ಆದುದು, ಕಳೆದುದು_20250208_071636.csv',
 'ಮಂಡಿ_ತೊಡೆ ಮತ್ತು ಕಣಕಾಲಿನ ಮಧ್ಯದ ಕೀಲುಸಂಧಿ_20250208_143354.csv',
 'ಮಂಡಿ_ಭಾರೀ ಪ್ರಮಾಣದ ವ್ಯಾಪಾರ ನಡೆಯುವ ಸ್ಥಳ_20250208_142858.csv',
 'ಮತ_caste_20250204_191824.csv',
 'ಮತ_ಅಭಿಪ್ರಾಯ, ಚುನಾವಣೆಗಳಲ್ಲಿ ಜನರು ತಮ್ಮ ಆಯ್ಕೆಯನ್ನು ಕುರಿತು ಸೂಚಿಸುವ ಅಭಿಪ್ರಾಯ_20250204_185717.csv',
 'ಮದ್ದು_ಅಗ್ನಿಸ್ಫೋಟಕ, ಸಿಡಿ ಮದ್ದು_20250208_140528.csv',
 'ಮದ್ದು_ಔಷಧ_20250208_141716.csv',
 'ಮುತ್ತು_ಚುಂಬನ_20250205_135934.csv',
 'ಮುತ್ತು_ನವರತ್ನಗಳಲ್ಲಿ ಒಂದು_20250205_141006.csv',
 'ಮೃಗ_ಒಂದು ಬಗೆಯ ಜಿಂಕೆ_20250202_185016.csv',
 'ಮೃಗ_ಪಶು_20250203_101513.csv',
 'ಯಂತ್ರ_ಕೆಲಸ ಮಾಡುವ ಸಾಧನ, ಉಪಕರಣ_20250207_050901.csv',
 'ಯಂತ್ರ_ತಾಯಿತಿ_20250207_050937.csv',
 'ಯಜಮಾನ_ಕುಟುಂಬದ ಮುಖ್ಯಸ್ಥ_20250202_172611.csv',
 'ಯಜಮಾನ_ಗಂಡ, ಪತಿ, ಮದುವೆಯಾದವ, ಇನಿಯ_20250202_173129.csv',
 'ಯಜಮಾನ_ಮಾಲೀಕ_20250202_175430.csv',
 'ಯಜಮಾನ_ಹಿರಿಯ_20250202_173154.csv',
 'ರಂಗ_ನಾಟಕ ಮುಂ.ವನ್ನು ಆಡುವ ಸ್ಥಳ, ವೇದಿಕೆ_20250203_102902.csv',
 'ರಂಗ_ಬಣ್ಣ_20250203_102959.csv',
 'ರಾಶಿ_ಜ್ಯೋತಿಷ್ಚಕ್ರದಲ್ಲಿರುವ) ಮೇಷ, ವೃಷಭ ಮೊ. ಹನ್ನೆರಡು ವಿಭಾಗಗಳು_20250206_205331.csv',
 'ರಾಶಿ_ಸಮೂಹ_20250206_204752.csv',
 'ಲಿಂಗ_Gender_20250206_130706.csv',
 'ಲಿಂಗ_ಶಿವನ ಒಂದು ಪ್ರತೀಕ_20250206_125852.csv',
 'ವರ_ಅನುಗ್ರಹ_20250207_130512.csv',
 'ವರ_ಮದುವೆಯ ಗಂಡು_20250207_123024.csv',
 'ವರ್ಷ_ಮಳೆ_20250208_120933.csv',
 'ವರ್ಷ_ಹನ್ನೆರಡು ತಿಂಗಳುಗಳ ಅವಧಿ_20250208_122034.csv',
 'ವಿಧಿ_ಪ್ರತಿಜ್ಞಾ ವಿಧಿ_20250208_183614.csv',
 'ವಿಧಿ_ವಿಧಿ ಲಿಖಿತ_20250208_182208.csv',
 'ವಿಧಿ_ವಿಧಿ ವಿಧಾನ_20250208_183014.csv',
 'ವಿಧಿ_ಸಂವಿಧಾನದ ವಿಧಿ_20250208_184534.csv',
 'ಸರಿ_ಅಂಬಲಿ, ಗಂಜಿ_20250203_183527.csv',
 'ಸರಿ_ಒಪ್ಪಿಗೆಯನ್ನೂ ಸಾಕೆಂಬುದನ್ನೂ ಸೂಚಿಸಲು ಬಳಸುವ ಶಬ್ದ_20250203_183348.csv',
 'ಸೀಮೆ_ಗಡಿ, ಸರಹದ್ದು_20250203_170146.csv',
 'ಸೀಮೆ_ವ್ಯತ್ಯಾಸ, ಭೇದ_20250203_175132.csv',
 'ಸುಪಾರಿ_ಅಡಕೆ_20250205_181545.csv',
 'ಸುಪಾರಿ_ಅಪರಾಧ ಮಾಡಲು ವೀಳೆಯ ನೀಡುವುದು, ಒಪ್ಪಂದ_20250205_182353.csv',
 'ಹಸಿ_ಆಹಾರವನ್ನು ಬಯಸು_20250205_185320.csv',
 'ಹಸಿ_ಹೊಸದು, ತಾಜಾ_20250205_190400.csv',
 'ಹುಟ್ಟು_ಜನನ_20250207_212547.csv',
 'ಹುಟ್ಟು_ದೋಣಿ ನಡೆಸುವ ಕೋಲು_20250207_213434.csv',
 'ಹೃದಯ_ದಯೆ, ಕರುಣೆ_20250202_083500.csv',
 'ಹೃದಯ_ದೇಹದ ಮಲಿನ ರಕ್ತವನ್ನು ಶುದ್ಧಗೊಳಿಸಿ ಅಂಗಾಂಗಳಿಗೆ ಶುದ್ಧರಕ್ತವನ್ನು ಒದಗಿಸುವ ರಕ್ತಕೋಶ_20250202_075726.csv',
 'ಹೊಳೆ_ಕಾಂತಿ, ಹೊಳಪು_20250207_220236.csv',
 'ಹೊಳೆ_ನದಿ, ತೊರೆ_20250207_221440.csv']

In [93]:
df_concat = pd.concat([pd.read_csv("D:/dai/New folder/csvs/"+f) for f in csv_files ], ignore_index=True)
df_concat

,word,sentence,kannada_meaning,english_meaning,is_correct,annotator,timestamp
0,ಅಕ್ಷರ,ಅವರು ಚಕ್ರವರ್ತಿ ಎನಿಸಿಕೊಂಡಳು ಮೊದಲು ಸುಧಾರಕ ತ್ಸಾ...,ಲಿಪಿ,Font,Yes,Darshan R K,2025-02-08 19:10:34
1,ಅಕ್ಷರ,ಯಾವಾಗಲೋ ತಂದಿಟ್ಟುಕೊಂಡಿದ್ದ ಎರಡೂವರೆ ರೂಪಾಯಿಯ ತಿಳಿನ...,ಲಿಪಿ,Font,Yes,Darshan R K,2025-02-08 19:10:34
2,ಅಕ್ಷರ,ಇನ್ನು ತುಳು ಓದಲು ಬರೆಯಲು ಆಸಕ್ತಿ ಇರುವವರಿಗಾಗಿ ಸ್ವರ...,ಲಿಪಿ,Font,Yes,Darshan R K,2025-02-08 19:10:34
3,ಅಕ್ಷರ,"ಇದರ ಜೊತೆಯಲ್ಲಿ, ಅಕ್ಷರ ಬರವಣಿಗೆಯಲ್ಲಿ ಸ್ವರಗಳ ಹೆಸರ...",ಲಿಪಿ,Font,Yes,Darshan R K,2025-02-08 19:10:35
4,ಅಕ್ಷರ,ಅದೇ ಯೋಜನೆಯ ಪ್ರಕಾರ ಮತ್ತು ದೊಡ್ಡ ಅಕ್ಷರ ಡಿ ಚಿತ...,ಲಿಪಿ,Font,Yes,Darshan R K,2025-02-08 19:10:35
...,...,...,...,...,...,...,...
4787,ಹೊಳೆ,ಈ ಚುನಾವಣೆಯಲ್ಲಿಯೂ ಮದ್ಯದ ಹೊಳೆ ಹರಿಸಲಾಗುತ್ತಿದೆ.,"ನದಿ, ತೊರೆ","river, stream",Yes,a,2025-02-07 22:14:40
4788,ಹೊಳೆ,ಹೀಗೆ ಹಾಯಾಗಿ ನಾವು ಹೊಳೆ ದಾಟುವೆವು ಎಂದ ಶಿವ.,"ನದಿ, ತೊರೆ","river, stream",Yes,a,2025-02-07 22:14:40
4789,ಹೊಳೆ,ಆದರೆ ನಿಮ್ಮ ಕೇಬಲ್ ಆಪರೇಟರ್ ಎಫ್‌ಟಿವಿ ಸೇವೆ ನೀಡದಿದ್...,"ನದಿ, ತೊರೆ","river, stream",Yes,a,2025-02-07 22:14:40
4790,ಹೊಳೆ,ಬಿಳಿನೆಲೆಯಲ್ಲಿ ಸ್ಥಳೀಯರು ಹೊಳೆ ದಾಟಲು ಉಪಯೋಗಿಸುತ್ತಿ...,"ನದಿ, ತೊರೆ","river, stream",Yes,a,2025-02-07 22:14:40
4791,ಹೊಳೆ,"ಇಲ್ಲಿನ ಮುರ್ಡೇಶ್ವರ, ವೆಂಕಟಾಪುರ, ಅಳ್ವೇಕೋಡಿ, ತೆಂಗಿ...","ನದಿ, ತೊರೆ","river, stream",Yes,a,2025-02-07 22:14:40

In [94]:
df_concat.is_correct.value_counts()

is_correct
Yes    4450
No      342
Name: count, dtype: int64

In [95]:
combined_v0 = df_concat[df_concat.is_correct == 'Yes'].to_csv("combined_v0.1.csv", index=False)

In [96]:
combined_v0 = df_concat[df_concat.is_correct == 'Yes']

In [97]:
combined_v0

,word,sentence,kannada_meaning,english_meaning,is_correct,annotator,timestamp
0,ಅಕ್ಷರ,ಅವರು ಚಕ್ರವರ್ತಿ ಎನಿಸಿಕೊಂಡಳು ಮೊದಲು ಸುಧಾರಕ ತ್ಸಾ...,ಲಿಪಿ,Font,Yes,Darshan R K,2025-02-08 19:10:34
1,ಅಕ್ಷರ,ಯಾವಾಗಲೋ ತಂದಿಟ್ಟುಕೊಂಡಿದ್ದ ಎರಡೂವರೆ ರೂಪಾಯಿಯ ತಿಳಿನ...,ಲಿಪಿ,Font,Yes,Darshan R K,2025-02-08 19:10:34
2,ಅಕ್ಷರ,ಇನ್ನು ತುಳು ಓದಲು ಬರೆಯಲು ಆಸಕ್ತಿ ಇರುವವರಿಗಾಗಿ ಸ್ವರ...,ಲಿಪಿ,Font,Yes,Darshan R K,2025-02-08 19:10:34
3,ಅಕ್ಷರ,"ಇದರ ಜೊತೆಯಲ್ಲಿ, ಅಕ್ಷರ ಬರವಣಿಗೆಯಲ್ಲಿ ಸ್ವರಗಳ ಹೆಸರ...",ಲಿಪಿ,Font,Yes,Darshan R K,2025-02-08 19:10:35
4,ಅಕ್ಷರ,ಅದೇ ಯೋಜನೆಯ ಪ್ರಕಾರ ಮತ್ತು ದೊಡ್ಡ ಅಕ್ಷರ ಡಿ ಚಿತ...,ಲಿಪಿ,Font,Yes,Darshan R K,2025-02-08 19:10:35
...,...,...,...,...,...,...,...
4787,ಹೊಳೆ,ಈ ಚುನಾವಣೆಯಲ್ಲಿಯೂ ಮದ್ಯದ ಹೊಳೆ ಹರಿಸಲಾಗುತ್ತಿದೆ.,"ನದಿ, ತೊರೆ","river, stream",Yes,a,2025-02-07 22:14:40
4788,ಹೊಳೆ,ಹೀಗೆ ಹಾಯಾಗಿ ನಾವು ಹೊಳೆ ದಾಟುವೆವು ಎಂದ ಶಿವ.,"ನದಿ, ತೊರೆ","river, stream",Yes,a,2025-02-07 22:14:40
4789,ಹೊಳೆ,ಆದರೆ ನಿಮ್ಮ ಕೇಬಲ್ ಆಪರೇಟರ್ ಎಫ್‌ಟಿವಿ ಸೇವೆ ನೀಡದಿದ್...,"ನದಿ, ತೊರೆ","river, stream",Yes,a,2025-02-07 22:14:40
4790,ಹೊಳೆ,ಬಿಳಿನೆಲೆಯಲ್ಲಿ ಸ್ಥಳೀಯರು ಹೊಳೆ ದಾಟಲು ಉಪಯೋಗಿಸುತ್ತಿ...,"ನದಿ, ತೊರೆ","river, stream",Yes,a,2025-02-07 22:14:40
4791,ಹೊಳೆ,"ಇಲ್ಲಿನ ಮುರ್ಡೇಶ್ವರ, ವೆಂಕಟಾಪುರ, ಅಳ್ವೇಕೋಡಿ, ತೆಂಗಿ...","ನದಿ, ತೊರೆ","river, stream",Yes,a,2025-02-07 22:14:40

In [98]:
def assign_sense_numbers(group):
    # Create a mapping of unique meanings to sense numbers
    unique_meanings = group['english_meaning'].unique()
    meaning_to_sense = {meaning: idx+1 for idx, meaning in enumerate(unique_meanings)}
    
    # Map each meaning to its sense number
    group['sense'] = group['english_meaning'].map(meaning_to_sense)
    return group

# Group by word and apply the numbering
combined_v0 = combined_v0.groupby('word').apply(assign_sense_numbers).reset_index(drop=True)

# Display the first few rows to verify
print(combined_v0[['word', 'english_meaning', 'sense']].head(100))

     word                         english_meaning  sense
0   ಅಕ್ಷರ                                    Font      1
1   ಅಕ್ಷರ                                    Font      1
2   ಅಕ್ಷರ                                    Font      1
3   ಅಕ್ಷರ                                    Font      1
4   ಅಕ್ಷರ                                    Font      1
..    ...                                     ...    ...
95    ಅಡಿ  Feet - 12 inches long measurement unit      1
96    ಅಡಿ  Feet - 12 inches long measurement unit      1
97    ಅಡಿ  Feet - 12 inches long measurement unit      1
98    ಅಡಿ  Feet - 12 inches long measurement unit      1
99    ಅಡಿ  Feet - 12 inches long measurement unit      1

[100 rows x 3 columns]

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_27552\4258847933.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  combined_v0 = combined_v0.groupby('word').apply(assign_sense_numbers).reset_index(drop=True)

In [99]:
combined_v0

,word,sentence,kannada_meaning,english_meaning,is_correct,annotator,timestamp,sense
0,ಅಕ್ಷರ,ಅವರು ಚಕ್ರವರ್ತಿ ಎನಿಸಿಕೊಂಡಳು ಮೊದಲು ಸುಧಾರಕ ತ್ಸಾ...,ಲಿಪಿ,Font,Yes,Darshan R K,2025-02-08 19:10:34,1
1,ಅಕ್ಷರ,ಯಾವಾಗಲೋ ತಂದಿಟ್ಟುಕೊಂಡಿದ್ದ ಎರಡೂವರೆ ರೂಪಾಯಿಯ ತಿಳಿನ...,ಲಿಪಿ,Font,Yes,Darshan R K,2025-02-08 19:10:34,1
2,ಅಕ್ಷರ,ಇನ್ನು ತುಳು ಓದಲು ಬರೆಯಲು ಆಸಕ್ತಿ ಇರುವವರಿಗಾಗಿ ಸ್ವರ...,ಲಿಪಿ,Font,Yes,Darshan R K,2025-02-08 19:10:34,1
3,ಅಕ್ಷರ,"ಇದರ ಜೊತೆಯಲ್ಲಿ, ಅಕ್ಷರ ಬರವಣಿಗೆಯಲ್ಲಿ ಸ್ವರಗಳ ಹೆಸರ...",ಲಿಪಿ,Font,Yes,Darshan R K,2025-02-08 19:10:35,1
4,ಅಕ್ಷರ,ಅದೇ ಯೋಜನೆಯ ಪ್ರಕಾರ ಮತ್ತು ದೊಡ್ಡ ಅಕ್ಷರ ಡಿ ಚಿತ...,ಲಿಪಿ,Font,Yes,Darshan R K,2025-02-08 19:10:35,1
...,...,...,...,...,...,...,...,...
4445,ಹೊಳೆ,ಈ ಚುನಾವಣೆಯಲ್ಲಿಯೂ ಮದ್ಯದ ಹೊಳೆ ಹರಿಸಲಾಗುತ್ತಿದೆ.,"ನದಿ, ತೊರೆ","river, stream",Yes,a,2025-02-07 22:14:40,2
4446,ಹೊಳೆ,ಹೀಗೆ ಹಾಯಾಗಿ ನಾವು ಹೊಳೆ ದಾಟುವೆವು ಎಂದ ಶಿವ.,"ನದಿ, ತೊರೆ","river, stream",Yes,a,2025-02-07 22:14:40,2
4447,ಹೊಳೆ,ಆದರೆ ನಿಮ್ಮ ಕೇಬಲ್ ಆಪರೇಟರ್ ಎಫ್‌ಟಿವಿ ಸೇವೆ ನೀಡದಿದ್...,"ನದಿ, ತೊರೆ","river, stream",Yes,a,2025-02-07 22:14:40,2
4448,ಹೊಳೆ,ಬಿಳಿನೆಲೆಯಲ್ಲಿ ಸ್ಥಳೀಯರು ಹೊಳೆ ದಾಟಲು ಉಪಯೋಗಿಸುತ್ತಿ...,"ನದಿ, ತೊರೆ","river, stream",Yes,a,2025-02-07 22:14:40,2
4449,ಹೊಳೆ,"ಇಲ್ಲಿನ ಮುರ್ಡೇಶ್ವರ, ವೆಂಕಟಾಪುರ, ಅಳ್ವೇಕೋಡಿ, ತೆಂಗಿ...","ನದಿ, ತೊರೆ","river, stream",Yes,a,2025-02-07 22:14:40,2

In [100]:
new_combined_v1 = combined_v0[["word", "sentence", "sense", "kannada_meaning", "english_meaning"]]

In [101]:
new_combined_v1 = new_combined_v1.rename(columns={"word": "lemma"})

In [102]:
# Group by lemma and get the maximum sense number for each
sense_counts = new_combined_v1.groupby('lemma')['sense'].max().sort_values(ascending=False)

# Display the results
print("Number of senses per lemma:")
print(sense_counts)

# Optional: Get some summary statistics
print("\nSummary:")
print(f"Total number of lemmas: {len(sense_counts)}")
print(f"Maximum number of senses for any lemma: {sense_counts.max()}")
print(f"Average number of senses per lemma: {sense_counts.mean():.2f}")

Number of senses per lemma:
lemma
ವಿಧಿ        4
ಭಾವ         4
ಕಣ          3
ಕೈಲಾಸ       3
ಗುಂಡಿ       3
ನಾಮ         3
ಯಜಮಾನ       3
ಬರೆ         2
ಬೆಳೆ        2
ಬಯಲು        2
ಯಂತ್ರ       2
ಭೂತ         2
ಮಂಡಿ        2
ಮತ          2
ಮದ್ದು       2
ಬದಿ         2
ಮುತ್ತು      2
ಮೃಗ         2
ಅಕ್ಷರ       2
ಪೂರ್ವ       2
ರಂಗ         2
ರಾಶಿ        2
ಲಿಂಗ        2
ವರ          2
ವರ್ಷ        2
ಸರಿ         2
ಸೀಮೆ        2
ಸುಪಾರಿ      2
ಹಸಿ         2
ಹುಟ್ಟು      2
ಹೃದಯ        2
ಬಂಡವಾಳ      2
ನೆರೆ        2
ನೇರ         2
ಅಡಿ         2
ಆಟ          2
ಉತ್ತರ       2
ಎಳೆ         2
ಕರ          2
ಕರ್ಮ        2
ಕಲೆ         2
ಕಳೆ         2
ಕಸರತ್ತು     2
ಕೂಲಿ        2
ಕೇಸರಿ       2
ಗಜ          2
ಗುಂಡು       2
ಗುಡುಗು      2
ಗುರು        2
ತಿಳಿ        2
ತೀರ್ಥ       2
ತುರಿ        2
ದಂತ         2
ದಳ          2
ದಿವಾಳಿ      2
ಧರಣಿ        2
ನರ          2
ನಿರ್ಮಾಪಕ    2
ಹೊಳೆ        2
ಅಶೋಕ        1
Name: sense, dtype: int64

Summary:
Total number of lemmas: 60
Maximum number of senses for any lemma: 4
Average number of senses per lemma: 2.13

In [103]:
# Filter to keep only lemmas with more than 1 sense
multi_sense_df = new_combined_v1[new_combined_v1['lemma'].isin(sense_counts[sense_counts > 1].index)]

# Count sentences per word per sense
sentence_counts = multi_sense_df.groupby(['lemma', 'sense']).size().reset_index(name='sentence_count')

# Sort by lemma and sense for better readability
sentence_counts = sentence_counts.sort_values(['lemma', 'sense'])

print("Number of sentences per lemma per sense:")
print(sentence_counts)

# Optional: Summary statistics
print("\nSummary:")
print(f"Total number of multi-sense lemmas: {len(sentence_counts['lemma'].unique())}")
print(f"Average sentences per sense: {sentence_counts['sentence_count'].mean():.2f}")

Number of sentences per lemma per sense:
      lemma  sense  sentence_count
0     ಅಕ್ಷರ      1              25
1     ಅಕ್ಷರ      2              36
2       ಅಡಿ      1              47
3       ಅಡಿ      2              34
4        ಆಟ      1              46
..      ...    ...             ...
122  ಹುಟ್ಟು      2               7
123    ಹೃದಯ      1              40
124    ಹೃದಯ      2              40
125    ಹೊಳೆ      1              36
126    ಹೊಳೆ      2              40

[127 rows x 3 columns]

Summary:
Total number of multi-sense lemmas: 59
Average sentences per sense: 35.01

In [104]:
multi_sense_df.to_csv("combined_v1.0.csv", index=False)

In [105]:
multi_sense_df

,lemma,sentence,sense,kannada_meaning,english_meaning
0,ಅಕ್ಷರ,ಅವರು ಚಕ್ರವರ್ತಿ ಎನಿಸಿಕೊಂಡಳು ಮೊದಲು ಸುಧಾರಕ ತ್ಸಾ...,1,ಲಿಪಿ,Font
1,ಅಕ್ಷರ,ಯಾವಾಗಲೋ ತಂದಿಟ್ಟುಕೊಂಡಿದ್ದ ಎರಡೂವರೆ ರೂಪಾಯಿಯ ತಿಳಿನ...,1,ಲಿಪಿ,Font
2,ಅಕ್ಷರ,ಇನ್ನು ತುಳು ಓದಲು ಬರೆಯಲು ಆಸಕ್ತಿ ಇರುವವರಿಗಾಗಿ ಸ್ವರ...,1,ಲಿಪಿ,Font
3,ಅಕ್ಷರ,"ಇದರ ಜೊತೆಯಲ್ಲಿ, ಅಕ್ಷರ ಬರವಣಿಗೆಯಲ್ಲಿ ಸ್ವರಗಳ ಹೆಸರ...",1,ಲಿಪಿ,Font
4,ಅಕ್ಷರ,ಅದೇ ಯೋಜನೆಯ ಪ್ರಕಾರ ಮತ್ತು ದೊಡ್ಡ ಅಕ್ಷರ ಡಿ ಚಿತ...,1,ಲಿಪಿ,Font
...,...,...,...,...,...
4445,ಹೊಳೆ,ಈ ಚುನಾವಣೆಯಲ್ಲಿಯೂ ಮದ್ಯದ ಹೊಳೆ ಹರಿಸಲಾಗುತ್ತಿದೆ.,2,"ನದಿ, ತೊರೆ","river, stream"
4446,ಹೊಳೆ,ಹೀಗೆ ಹಾಯಾಗಿ ನಾವು ಹೊಳೆ ದಾಟುವೆವು ಎಂದ ಶಿವ.,2,"ನದಿ, ತೊರೆ","river, stream"
4447,ಹೊಳೆ,ಆದರೆ ನಿಮ್ಮ ಕೇಬಲ್ ಆಪರೇಟರ್ ಎಫ್‌ಟಿವಿ ಸೇವೆ ನೀಡದಿದ್...,2,"ನದಿ, ತೊರೆ","river, stream"
4448,ಹೊಳೆ,ಬಿಳಿನೆಲೆಯಲ್ಲಿ ಸ್ಥಳೀಯರು ಹೊಳೆ ದಾಟಲು ಉಪಯೋಗಿಸುತ್ತಿ...,2,"ನದಿ, ತೊರೆ","river, stream"
4449,ಹೊಳೆ,"ಇಲ್ಲಿನ ಮುರ್ಡೇಶ್ವರ, ವೆಂಕಟಾಪುರ, ಅಳ್ವೇಕೋಡಿ, ತೆಂಗಿ...",2,"ನದಿ, ತೊರೆ","river, stream"

In [106]:
sentence_counts

      lemma  sense  sentence_count
0     ಅಕ್ಷರ      1              25
1     ಅಕ್ಷರ      2              36
2       ಅಡಿ      1              47
3       ಅಡಿ      2              34
4        ಆಟ      1              46
..      ...    ...             ...
122  ಹುಟ್ಟು      2               7
123    ಹೃದಯ      1              40
124    ಹೃದಯ      2              40
125    ಹೊಳೆ      1              36
126    ಹೊಳೆ      2              40

[127 rows x 3 columns]

In [107]:
# First get counts per lemma and sense
sentence_counts = multi_sense_df.groupby(['lemma', 'sense']).size().reset_index(name='sentence_count')

# Find lemmas where ANY sense has less than 10 instances
lemmas_to_remove = sentence_counts[sentence_counts['sentence_count'] < 1]['lemma'].unique()

# Remove these lemmas from our dataframe
filtered_df = multi_sense_df[~multi_sense_df['lemma'].isin(lemmas_to_remove)]

# Get new counts after filtering
final_counts = filtered_df.groupby(['lemma', 'sense']).size().reset_index(name='sentence_count')

# Sort by lemma and sense for better readability
final_counts = final_counts.sort_values(['lemma', 'sense'])

print("Number of sentences per lemma per sense (after filtering):")
print(final_counts)

# Summary statistics
print("\nSummary:")
print(f"Total number of remaining lemmas: {len(final_counts['lemma'].unique())}")
print(f"Average sentences per sense: {final_counts['sentence_count'].mean():.2f}")

Number of sentences per lemma per sense (after filtering):
      lemma  sense  sentence_count
0     ಅಕ್ಷರ      1              25
1     ಅಕ್ಷರ      2              36
2       ಅಡಿ      1              47
3       ಅಡಿ      2              34
4        ಆಟ      1              46
..      ...    ...             ...
122  ಹುಟ್ಟು      2               7
123    ಹೃದಯ      1              40
124    ಹೃದಯ      2              40
125    ಹೊಳೆ      1              36
126    ಹೊಳೆ      2              40

[127 rows x 3 columns]

Summary:
Total number of remaining lemmas: 59
Average sentences per sense: 35.01

In [108]:
len(final_counts.lemma.unique())

59

In [109]:
filtered_df

,lemma,sentence,sense,kannada_meaning,english_meaning
0,ಅಕ್ಷರ,ಅವರು ಚಕ್ರವರ್ತಿ ಎನಿಸಿಕೊಂಡಳು ಮೊದಲು ಸುಧಾರಕ ತ್ಸಾ...,1,ಲಿಪಿ,Font
1,ಅಕ್ಷರ,ಯಾವಾಗಲೋ ತಂದಿಟ್ಟುಕೊಂಡಿದ್ದ ಎರಡೂವರೆ ರೂಪಾಯಿಯ ತಿಳಿನ...,1,ಲಿಪಿ,Font
2,ಅಕ್ಷರ,ಇನ್ನು ತುಳು ಓದಲು ಬರೆಯಲು ಆಸಕ್ತಿ ಇರುವವರಿಗಾಗಿ ಸ್ವರ...,1,ಲಿಪಿ,Font
3,ಅಕ್ಷರ,"ಇದರ ಜೊತೆಯಲ್ಲಿ, ಅಕ್ಷರ ಬರವಣಿಗೆಯಲ್ಲಿ ಸ್ವರಗಳ ಹೆಸರ...",1,ಲಿಪಿ,Font
4,ಅಕ್ಷರ,ಅದೇ ಯೋಜನೆಯ ಪ್ರಕಾರ ಮತ್ತು ದೊಡ್ಡ ಅಕ್ಷರ ಡಿ ಚಿತ...,1,ಲಿಪಿ,Font
...,...,...,...,...,...
4445,ಹೊಳೆ,ಈ ಚುನಾವಣೆಯಲ್ಲಿಯೂ ಮದ್ಯದ ಹೊಳೆ ಹರಿಸಲಾಗುತ್ತಿದೆ.,2,"ನದಿ, ತೊರೆ","river, stream"
4446,ಹೊಳೆ,ಹೀಗೆ ಹಾಯಾಗಿ ನಾವು ಹೊಳೆ ದಾಟುವೆವು ಎಂದ ಶಿವ.,2,"ನದಿ, ತೊರೆ","river, stream"
4447,ಹೊಳೆ,ಆದರೆ ನಿಮ್ಮ ಕೇಬಲ್ ಆಪರೇಟರ್ ಎಫ್‌ಟಿವಿ ಸೇವೆ ನೀಡದಿದ್...,2,"ನದಿ, ತೊರೆ","river, stream"
4448,ಹೊಳೆ,ಬಿಳಿನೆಲೆಯಲ್ಲಿ ಸ್ಥಳೀಯರು ಹೊಳೆ ದಾಟಲು ಉಪಯೋಗಿಸುತ್ತಿ...,2,"ನದಿ, ತೊರೆ","river, stream"
4449,ಹೊಳೆ,"ಇಲ್ಲಿನ ಮುರ್ಡೇಶ್ವರ, ವೆಂಕಟಾಪುರ, ಅಳ್ವೇಕೋಡಿ, ತೆಂಗಿ...",2,"ನದಿ, ತೊರೆ","river, stream"

In [110]:
filtered_df.to_csv("kannada_polsemy_dai_v1.1.csv", index=False)

In [111]:
def find_word_position(row):
    sentence = row['sentence']
    lemma = row['lemma']
    
    # Find the start position of the lemma in the sentence
    start = sentence.find(lemma)
    if start != -1:
        end = start + len(lemma)
    else:
        # If lemma not found exactly, set to -1
        start = -1
        end = -1
    
    return pd.Series({'start': start, 'end': end})

# Add start and end positions
position_df = filtered_df.copy()
position_df[['start', 'end']] = filtered_df.apply(find_word_position, axis=1)

# Group by lemma and sense
final_counts = position_df.groupby(['lemma', 'sense']).size().reset_index(name='count')

# Print a few examples to verify
print("\nFirst few rows with position information:")
print(position_df[['lemma', 'sense', 'sentence', 'start', 'end']].head(10))

# Print summary of words and their counts
print("\nCounts per lemma and sense:")
print(final_counts)

First few rows with position information:
   lemma  sense                                           sentence  start  end
0  ಅಕ್ಷರ      1  ಅವರು ಚಕ್ರವರ್ತಿ ಎನಿಸಿಕೊಂಡಳು ಮೊದಲು ಸುಧಾರಕ ತ್ಸಾ...    187  192
1  ಅಕ್ಷರ      1  ಯಾವಾಗಲೋ ತಂದಿಟ್ಟುಕೊಂಡಿದ್ದ ಎರಡೂವರೆ ರೂಪಾಯಿಯ ತಿಳಿನ...    130  135
2  ಅಕ್ಷರ      1  ಇನ್ನು ತುಳು ಓದಲು ಬರೆಯಲು ಆಸಕ್ತಿ ಇರುವವರಿಗಾಗಿ ಸ್ವರ...     66   71
3  ಅಕ್ಷರ      1  ಇದರ ಜೊತೆಯಲ್ಲಿ, ಅಕ್ಷರ ಬರವಣಿಗೆಯಲ್ಲಿ ಸ್ವರಗಳ ಹೆಸರ...     16   21
4  ಅಕ್ಷರ      1  ಅದೇ ಯೋಜನೆಯ ಪ್ರಕಾರ ಮತ್ತು ದೊಡ್ಡ ಅಕ್ಷರ ಡಿ ಚಿತ...     34   39
5  ಅಕ್ಷರ      1                        ಅದೂ ಅಕ್ಷರ ರೂಪದ ಮಾತೇ ಅಲ್ಲವೇ?      4    9
6  ಅಕ್ಷರ      1             ಮಕ್ಕಳು ಇಂಗ್ಲಿಷ್‌ ಅಕ್ಷರ ಗುರುತಿಸುತ್ತಾರೆ.     17   22
7  ಅಕ್ಷರ      1  ಸಮಾಜ ಕಲ್ಯಾಣ ಇಲಾಖೆಯಲ್ಲಿ ಅಕ್ಷರ ಬರದವರಿಗೆ ವಾರ್ಡನ್ ...     23   28
8  ಅಕ್ಷರ      1  - ಹೆಸರು ಆರಂಭದಲ್ಲಿ ಅಕ್ಷರ ಅಥವಾ ಅಂಕಿಯ ಎಂದು, ಮತ್ತು...     18   23
9  ಅಕ್ಷರ      1  ಈ ಗ್ರಂಥವನ್ನು ಅಂದವಾಗಿ ಅಕ್ಷರ ಜೋಡಣೆ ಹಾಗೂ ಮುದ್ರಣ ಮ...     21   26

Counts per lemma and sense:
      lemma  sense  count
0     ಅಕ್ಷರ      1     25
1     ಅಕ್ಷರ      2     36
2       ಅಡಿ      1     47
3       ಅಡಿ      2     34
4        ಆಟ      1     46
..      ...    ...    ...
122  ಹುಟ್ಟು      2      7
123    ಹೃದಯ      1     40
124    ಹೃದಯ      2     40
125    ಹೊಳೆ      1     36
126    ಹೊಳೆ      2     40

[127 rows x 3 columns]

In [112]:
position_df.to_csv("kannada_polsemy_dai_v1.1.csv", index=False)

In [113]:
def find_word_position(row):
    sentence = row['sentence']
    lemma = row['lemma']
    
    # Find the start position of the lemma in the sentence
    start = sentence.find(lemma)
    if start != -1:
        # For Kannada words, we need to count the actual characters
        # not the byte positions
        end = start + len(lemma)
        # Verify the extracted word matches the lemma
        extracted_word = sentence[start:end]
        if extracted_word != lemma:
            start = -1
            end = -1
    else:
        start = -1
        end = -1
    
    return pd.Series({'start': start, 'end': end})

# Add start and end positions
position_df = filtered_df.copy()
position_df[['start', 'end']] = filtered_df.apply(find_word_position, axis=1)

# Let's verify the extraction is correct
def verify_positions(row):
    if row['start'] != -1:
        extracted = row['sentence'][row['start']:row['end']]
        return extracted == row['lemma']
    return False

# Print some examples to verify
print("Sample results with extracted words:")
for _, row in position_df.head(10).iterrows():
    if row['start'] != -1:
        extracted = row['sentence'][row['start']:row['end']]
        print(f"\nLemma: {row['lemma']}")
        print(f"Sentence: {row['sentence']}")
        print(f"Start: {row['start']}, End: {row['end']}")
        print(f"Extracted word: {extracted}")
        print(f"Match correct: {row['lemma'] == extracted}")

Sample results with extracted words:

Lemma: ಅಕ್ಷರ
Sentence: ಅವರು ಚಕ್ರವರ್ತಿ ಎನಿಸಿಕೊಂಡಳು ಮೊದಲು ಸುಧಾರಕ ತ್ಸಾರ್ ಪೀಟರ್ I ರೊಂದಿಗೆ ರಶಿಯಾದಲ್ಲಿ ಸಾಂಕೇತಿಕಾಕ್ಷರಗಳನ್ನೊಳಗೊಂಡಿದೆ ನೋಟವನ್ನು ಸಾಮಾನ್ಯವಾಗಿ ಸಂಬಂಧ, ವೈಯಕ್ತಿಕ ಸಾಂಕೇತಿಕಾಕ್ಷರಗಳ ಪೀಟರ್ ನಾನು ಲ್ಯಾಟಿನ್ ಅಕ್ಷರ ಪಿ ಪ್ರತಿಬಿಂಬದ ಒಳಗೊಂಡಿತ್ತು.
Start: 187, End: 192
Extracted word: ಅಕ್ಷರ
Match correct: True

Lemma: ಅಕ್ಷರ
Sentence: ಯಾವಾಗಲೋ ತಂದಿಟ್ಟುಕೊಂಡಿದ್ದ ಎರಡೂವರೆ ರೂಪಾಯಿಯ ತಿಳಿನೀಲಿ ಅಂತರ್ದೇಶಿ ಪತ್ರದಲ್ಲಿ, ಸಾಲು ಡೊಂಕಾಗದ ಹಾಗೆ, ಒತ್ತಕ್ಷರ ಕೆಳಗಿನ ಸಾಲಿಗೆ ಅಡ್ಡಿಪಡಿಸದ ಹಾಗೆ, ಅಕ್ಷರ ವಕ್ರ ಹೋಗದ ಹಾಗೆ, ವ್ಯಾಕರಣ ತಪ್ಪಾಗದ ಹಾಗೆ ಎಚ್ಚರಿಕೆಯಿಂದ ಯೋಚಿಸಿ ಯೋಚಿಸಿ ಬರೆಯುತ್ತಿದ್ದಾಳೆ.
Start: 130, End: 135
Extracted word: ಅಕ್ಷರ
Match correct: True

Lemma: ಅಕ್ಷರ
Sentence: ಇನ್ನು ತುಳು ಓದಲು ಬರೆಯಲು ಆಸಕ್ತಿ ಇರುವವರಿಗಾಗಿ ಸ್ವರಗಳು, ವ್ಯಂಜನಗಳು, ಇತರ ಅಕ್ಷರಗಳು, ಲೇಖನ ಚಿಹ್ನೆಗಳು, ಉದ್ಧರಣ ಚಿಹ್ನೆಗಳು ಹಾಗೂ ಅಕ್ಷರ ಬಳಕೆಯ ವಿಧಾನಗಳನ್ನು ಕೂಡ ಇದರಲ್ಲಿ ವಿವರಿಸಲಾಗಿದೆ.
Start: 66, End: 71
Extracted word: ಅಕ್ಷರ
Match correct: True

Lemma: ಅಕ್ಷರ
Sentence: ಇದರ ಜೊತೆಯಲ್ಲಿ, ಅಕ್ಷರ ಬರವಣಿಗೆಯಲ್ಲಿ ಸ್ವರಗಳ ಹೆಸರಿನ ಹಲವು ರೂಢಿಗಳು ಒತ್ತಡದ ಉಪಸ್ಥಿತಿ ಅಥವಾ ಅನುಪಸ್ಥಿತಿಯನ್ನು ಅವಲಂಬಿಸಿರುತ್ತದೆ.
Start: 16, End: 21
Extracted word: ಅಕ್ಷರ
Match correct: True

Lemma: ಅಕ್ಷರ
Sentence: ಅದೇ ಯೋಜನೆಯ ಪ್ರಕಾರ ಮತ್ತು ದೊಡ್ಡ ಅಕ್ಷರ ಡಿ ಚಿತ್ರಿಸುವ ಲೋಗೋ ಮಾಸ್ಕೋ ಡೈನಮೊ ಹೋದರು.
Start: 34, End: 39
Extracted word: ಅಕ್ಷರ
Match correct: True

Lemma: ಅಕ್ಷರ
Sentence: ಅದೂ ಅಕ್ಷರ ರೂಪದ ಮಾತೇ ಅಲ್ಲವೇ?
Start: 4, End: 9
Extracted word: ಅಕ್ಷರ
Match correct: True

Lemma: ಅಕ್ಷರ
Sentence: ಮಕ್ಕಳು ಇಂಗ್ಲಿಷ್‌ ಅಕ್ಷರ ಗುರುತಿಸುತ್ತಾರೆ.
Start: 17, End: 22
Extracted word: ಅಕ್ಷರ
Match correct: True

Lemma: ಅಕ್ಷರ
Sentence: ಸಮಾಜ ಕಲ್ಯಾಣ ಇಲಾಖೆಯಲ್ಲಿ ಅಕ್ಷರ ಬರದವರಿಗೆ ವಾರ್ಡನ್ ಜವಾಬ್ದಾರಿ ನೀಡಿದ್ದು, ಅವರ ಬದಲಿಗೆ ಹೊಸದಾಗಿ ನೇಮಕವಾಗಿರುವ ಅಡುಗೆಯವರು ಪಿಯುಸಿ, ಪದವಿ ಶಿಕ್ಷಣ ಪಡೆದಿದ್ದು, ಅಂತಹವರಿಗೆ ಜವಾಬ್ದಾರಿ ನೀಡುವಂತೆ ಸಮಾಜ ಕಲ್ಯಾಣ ಇಲಾಖೆಯ ಜಂಟಿ ನಿರ್ದೇಶಕರಾದ ಸಿಂಧು ಅವರಿಗೆ ತಿಳಿಸಿದರು.
Start: 23, End: 28
Extracted word: ಅಕ್ಷರ
Match correct: True

Lemma: ಅಕ್ಷರ
Sentence: - ಹೆಸರು ಆರಂಭದಲ್ಲಿ ಅಕ್ಷರ ಅಥವಾ ಅಂಕಿಯ ಎಂದು, ಮತ್ತು ಇದು ಬಾಹ್ಯಾಕಾಶ ಮತ್ತು ವಿಶೇಷ ಐಟಂಗಳನ್ನು ಜೊತೆಗೆ, ಯಾವುದೇ ASCII ಅಕ್ಷರ ಹಾಜರಿದ್ದರು ಮಾಡಬಹುದು ಇನ್ ಮಾಡಬೇಕು;
Start: 18, End: 23
Extracted word: ಅಕ್ಷರ
Match correct: True

Lemma: ಅಕ್ಷರ
Sentence: ಈ ಗ್ರಂಥವನ್ನು ಅಂದವಾಗಿ ಅಕ್ಷರ ಜೋಡಣೆ ಹಾಗೂ ಮುದ್ರಣ ಮಾಡಿಕೊಟ್ಟ ಮಿತ್ರರಿಗೂ ವಂದನೆಗಳು
Start: 21, End: 26
Extracted word: ಅಕ್ಷರ
Match correct: True

In [114]:
position_df.to_csv("kannada_polsemy_dai_v1.1.csv", index=False)